### ISSUE TITLE
simpleRouting needs a louder entry.

### ISSUE THREAD

**Issue by mfvargo** [actionhero/www.actionherojs.com#173]
simpleRouting is a pretty far reaching setting.  Knowing that it basically defeats routes.js verbs should be called out in the docs.  I would suggest in the routes section of https://www.actionherojs.com/tutorials/web-server#Routes adding simpleRouting and it's effect in the bullet list of "This variables in play here"

**Comment by evantahler** [comment]
Simple routing is to be removed per https://github.com/actionhero/actionhero/discussions/1579
